#!/bin/bash

test "${no_config:-0}" == 1
CONFIG=$?
test "${no_config_secret:-0}" == 1
CONFIG_SECRET=$?
ES_TRUSTED_CA_CERT_FILES=()
IFS=',' read -r -a ES_TRUSTED_CA_CERT_FILES <<< "${es_trusted_ca_cert_files:-$es_trusted_ca_cert_file}"
test "${no_config_es:-0}" == 1
CONFIG_ES=$?
ES_URI=${es_uri:-}
ES_HOSTNAME=${es_hostname:-elasticsearch}
CONFIG_FILE=${config_file:-/etc/cortex/application.conf}
DEFAULT_ANALYZER_URL="https://download.thehive-project.org/analyzers.json"
ANALYZER_URLS=()
IFS=',' read -r -a ANALYZER_URLS <<< "${analyzer_urls:-$analyzer_url}"
DEFAULT_RESPONDER_URL="https://download.thehive-project.org/responders.json"
RESPONDER_URLS=()
IFS=',' read -r -a RESPONDER_URLS <<< "${responder_urls:-$responder_url}"
START_DOCKER=${start_docker:-0}
SHOW_SECRET=${show_secret:-0}
DAEMON_USER=${daemon_user:-cortex}
JOB_DIRECTORY=${job_directory:-/tmp/cortex-jobs}
DOCKER_JOB_DIRECTORY=${docker_job_directory:-}

function usage {
  cat <<- _EOF_
    Available options:
    --no-config                  | do not configure TheHive (add secret and elasticsearch)
    --no-config-secret           | do not add random secret to configuration
    --no-config-es               | do not add elasticsearch hosts to configuration
    --es-uri <uri>               | use this string to configure elasticsearch hosts (format: http(s)://host:port,host:port(/prefix)?querystring)
    --es-trust-ca-cert <file.pem>| trust a CA for outbound Elasticsearch TLS connections (can use multiple times)
    --es-hostname <host>         | resolve this hostname to find elasticsearch instances
    --secret <secret>            | secret to secure sessions
    --show-secret                | show the generated secret
    --job-directory <dir>        | use this directory to store job files
    --docker-job-directory <dir> | indicate the job directory in the host (not inside container)
    --analyzer-url <url>         | where analyzers are located (url or path)
    --responder-url <url>        | where responders are located (url or path)
    --start-docker               | start a internal docker (inside container) to run analyzers/responders
    --daemon-user <user>         | run cortex using this user
_EOF_
  exit 1
}

STOP=0
while test $# -gt 0 -o $STOP = 1
do
  case "$1" in
    "--no-config")            CONFIG=0;;
    "--no-config-secret")     CONFIG_SECRET=0;;
    "--no-config-es")         CONFIG_ES=0;;
    "--es-hosts")             echo "--es-hosts is deprecated, please use --es-uri"
                              usage;;
    "--es-uri")               shift; ES_URI=$1;;
    "--es-trust-ca-cert")        shift; ES_TRUSTED_CA_CERT_FILES+=($1);;
    "--es-hostname")          shift; ES_HOSTNAME=$1;;
    "--secret")               shift; SECRET=$1;;
    "--show-secret")          SHOW_SECRET=1;;
    "--job-directory")        shift; JOB_DIRECTORY=$1;;
    "--docker-job-directory") shift; DOCKER_JOB_DIRECTORY=$1;;
    "--analyzer-path")        echo "--analyzer-path is deprecated, please use --analyzer-url"
                              shift; ANALYZER_URLS+=("$1");;
    "--responder-path")       echo "--responder-path is deprecated, please use --responder-url"
                              shift; RESPONDER_URLS+=("$1");;
    "--analyzer-url")         shift; ANALYZER_URLS+=("$1");;
    "--responder-url")        shift; RESPONDER_URLS+=("$1");;
    "--start-docker")         START_DOCKER=1;;
    "--daemon-user")          shift; DAEMON_USER=$1;;
    "--")                     STOP=1;;
    *)                        echo "unrecognized option: $1"; usage;;
  esac
  shift
done

if test $CONFIG = 1
then
  CONFIG_FILE=$(mktemp --tmpdir cortex-XXXXXX.conf)
  if test $CONFIG_SECRET = 1
  then
    if test -z "$SECRET"
    then
      SECRET=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 64 | head -n 1)
      test $SHOW_SECRET = 1 && echo "Using secret: $SECRET"
    fi
    echo "play.http.secret.key=\"$SECRET\"" >> "$CONFIG_FILE"
  fi

  if test $CONFIG_ES = 1
  then
    if test -z "$ES_URI"
    then
      function join_es_hosts {
        echo -n "$1:9200"
        shift
        printf "%s," "${@/#/:9200}"
      }

      ES=$(getent ahostsv4 "$ES_HOSTNAME" | awk '{ print $1 }' | sort -u)
      if test -z "$ES"
      then
        echo "Warning automatic elasticsearch host config fails"
      else
        ES_URI=http://$(join_es_hosts "$ES")
      fi
    fi
    if test -n "$ES_URI"
    then
      echo "Using elasticsearch uri: $ES_URI"
      echo "search.uri=\"$ES_URI\"" >> "$CONFIG_FILE"
    else
      echo elasticsearch host not configured
    fi

    if test ${#ES_TRUSTED_CA_CERT_FILES} -gt 0
    then
      # elastic4play only lets us specify one truststore, so let's
      # make it a JKS with whatever is needed inside it
      echo "Creating trust store"
      ES_TRUST_STORE_PASSWORD=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 64 | head -n 1)
      ES_TRUST_STORE=$(mktemp --tmpdir cortex-XXXXXX.ts)
      # yes, removing this temp file could cause a race condition, but
      # keytool won't work if the file exists
      rm -f $ES_TRUST_STORE
      for cacert_pem_file in "${ES_TRUSTED_CA_CERT_FILES[@]}"
      do
          keytool -importcert -keystore $ES_TRUST_STORE \
                  -file $cacert_pem_file \
                  -alias $(basename $cacert_pem_file) \
                  -storepass $ES_TRUST_STORE_PASSWORD -noprompt
      done
      # ssl context is only set up if keyStore given: see
      # sslContextMaybe,
      # .../app/org/elastic4play/database/DBConfiguration.scala. we
      # won't have any certs with private keys in this trust store,
      # but that's ok. change this if ES client cert support is added
      # to this script.
      echo "search.keyStore.path=\"$ES_TRUST_STORE\"" >> "$CONFIG_FILE"
      echo "search.keyStore.type=\"JKS\"" >> "$CONFIG_FILE"
      echo "search.keyStore.password=\"$ES_TRUST_STORE_PASSWORD\"" >> "$CONFIG_FILE"
      echo "search.trustStore.path=\"$ES_TRUST_STORE\"" >> "$CONFIG_FILE"
      echo "search.trustStore.type=\"JKS\"" >> "$CONFIG_FILE"
      echo "search.trustStore.password=\"$ES_TRUST_STORE_PASSWORD\"" >> "$CONFIG_FILE"
    fi
  fi

  test -n "$JOB_DIRECTORY" && echo "job.directory=\"$JOB_DIRECTORY\"" >> "$CONFIG_FILE"
  test -n "$DOCKER_JOB_DIRECTORY" && echo "job.dockerDirectory=\"$DOCKER_JOB_DIRECTORY\"" >> "$CONFIG_FILE"

  function join_urls {
    echo -n "\"$1\""
    shift
    for U do echo -n ",\"$U\""; done
#    printf ",\"%s\"" $@
  }
  test ${#ANALYZER_URLS} = 0 && ANALYZER_URLS+=("$DEFAULT_ANALYZER_URL")
  echo "analyzer.urls=[$(join_urls "${ANALYZER_URLS[@]}")]" >> "$CONFIG_FILE"

  test ${#RESPONDER_URLS} = 0 && RESPONDER_URLS+=("$DEFAULT_RESPONDER_URL")
  echo "responder.urls=[$(join_urls "${RESPONDER_URLS[@]}")]" >> "$CONFIG_FILE"

  echo 'include file("/etc/cortex/application.conf")' >> "$CONFIG_FILE"
fi

if test $START_DOCKER = 1
then
  usermod --append --groups docker "$DAEMON_USER"
  dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &> /dev/null &
  DOCKER_PID=$!
fi

echo config file is:
cat "$CONFIG_FILE"
touch /var/log/cortex/application.log
chown -R "$DAEMON_USER" /var/log/cortex
chown -R "$DAEMON_USER" /etc/cortex
chown -R "$DAEMON_USER" "$CONFIG_FILE"
test -n "$ES_TRUST_STORE" && chown "$DAEMON_USER" "$ES_TRUST_STORE"
test -e /var/run/docker.sock && chown "$DAEMON_USER" /var/run/docker.sock
if test -n "$JOB_DIRECTORY"
then
  mkdir -p "$JOB_DIRECTORY"
  chown -R "$DAEMON_USER" "$JOB_DIRECTORY"
fi

su "$DAEMON_USER" -c "bin/cortex \
  -Dconfig.file=$CONFIG_FILE \
  -Dlogger.file=/etc/cortex/logback.xml \
  -Dpidfile.path=/dev/null \
  $*"

test $START_DOCKER = 1 && kill ${DOCKER_PID}
