name: Build packages
on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        timeout-minutes: 15
        continue-on-error: true
        with:
          node-version: 18.16
      - name: Install bower
        run: npm install -g bower
      - name: Import PGP Key
        run: |
          export GPG_TTY=$(tty)
          gpg --batch --import - <<< $PGP_KEY
        env:
          PGP_KEY: ${{ secrets.PGP_KEY }}
      - name: Write version
        id: version
        run: |
          V=$(sbt -no-colors --error "print version" | awk 'END{print $1}')
          echo "version=$V"
          echo "version=$V" >> $GITHUB_OUTPUT
      - name: Build packages
        run: ./sbt Debian/packageBin Rpm/packageBin Universal/packageBin makeBom
      - name: Move packages
        run: |
          mv target/rpm/RPMS/noarch/cortex*.rpm target/
          mv target/universal/cortex*.zip target/

      - name: Make github release
        if: github.ref_type == 'tag'
        uses: "softprops/action-gh-release@v1"
        id: make-release
        with:
          generate_release_notes: true
          files: |
            target/cortex*.deb
            target/cortex*.rpm
            target/cortex*.zip
            target/cortex*.bom.xml

      - name: Store artifacts
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            target/cortex*.deb
            target/cortex*.rpm
            target/cortex*.zip
            target/cortex*.bom.xml
          retention-days: 5

  notify:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    if: always()
    steps:
      - name: Slack notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          channel: "#ci-cortex"
          name: Cortex build
          include_commit_message: true
          include_jobs: true