name: misc.sync
on:
  # Run manually a sync between current repo / develop and public repo develop
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "19 22 * * *"
jobs:
  sync:
    permissions:
      actions: read
      contents: write
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
      - name: Pull down public Cortex repo content
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo sync StrangeBee/Cortex --source thehive-project/cortex --branch develop --force
